name: rebuild

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: post docker build trigger
        env:
          TRIGGER_URL: ${{ secrets.DOCKER_HUB_BUILD_TRIGGER_URL }}
        run: make rebuild
